openapi: 3.0.1
info:
  title: MedKG API
  version: 1.0.0
paths:
  /list/labels:
    get:
      summary: Get all labels
      responses:
        '200':
          description: A list of labels
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /list/relations:
    get:
      summary: Get all relations
      responses:
        '200':
          description: A list of relations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /list/labels/{label}:
    get:
      summary: Get all nodes with a specific label
      parameters:
        - name: label
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of nodes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Node'
  /nodes/graph:
    get:
      summary: Get the graph of all nodes
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
        - name: term
          in: query
          schema:
            type: string
      responses:
        '200':
          description: A list of nodes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Node'
  /nodes/search:
    get:
      summary: Get the graph of all nodes
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
        - name: term
          in: query
          schema:
            type: string
      responses:
        '200':
          description: A list of nodes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Node'
  /nodes:
    post:
      summary: Fetch Nodes for a request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NodeRequest'
      responses:
        '201':
          description: Node created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
  
components:
  schemas:
    Node:
      type: object
      properties:
        id:
          type: string
        properties:
          type: object
    NodeRequest:
      type: object
      properties:
        label:
          type: string
        limit:
          type: integer
          format: int32
          minimum: 1
          maximum: 100
